spring:
  application:
    name: "configserver"
  profiles:
    active: git
  # active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/DevSkillsLearning/easybank-config.git"
          timeout: 5
          clone-on-start: true
          force-pull: true
          username: "chauhan.devam@gmail.com"
          password: "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"
          default-label: main
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

encrypt:
  key: "2x9OJV4KDke26T+5KM4kdwnpNtnMY8RjP5mG7UNLANgxH+kwtQ/htsOFPyQmS0up"

#        native:
#          search-locations: "classpath:/config"


server:
  port: 8071

