spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
        # search-locations: "classpath:/config"
        # search-locations: "file:///Users//eazybytes//Documents//config"
        git:
          uri: "https://github.com/DevSkillsLearning/easybank-config.git"
          timeout: 5
          clone-on-start: true
          force-pull: true
          username: "chauhan.devam@gmail.com"
          password: "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"
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

server:
  port: 8071
